version: '3'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: book
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3307:3306"  # Maps host port 3306 to container port 3306
    volumes:
      - mysql-data:/var/lib/mysql
  bookstore-app:
    image: bookstore-app
    build: .
    ports:
      - "9090:9090"
    depends_on:
      - mysql
    environment:
      # Using “mysql” as hostname allows the service to reach the MySQL container over the Docker network.
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/book
      SPRING_DATASOURCE_USERNAME: myuser
      SPRING_DATASOURCE_PASSWORD: mypassword

volumes:
  mysql-data:
